spring:
  application:
    name: smartApi
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/contact_api?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin

# useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    async:
      request-timeout: 3600000
  
  web:
    resources:
      add-mappings: false   
      
server:
  port: 8080
  error: 
    path: /user/error
    whitelabel:
      enabled: false
